import type { AgentItem, AgentsSnapshot } from "../../shared/agents/models";
import type { PluginTheme } from "@getpaseo/plugin";
import { requestForm } from "../../shared/agents/questions";

export const light: PluginTheme = {
  colors: {
    surface0: "#fafafa",
    surface1: "#ffffff",
    surface2: "#edf1f5",
    border: "#d5dae0",
    foreground: "#17212b",
    foregroundMuted: "#536373",
    accent: "#245e98",
    accentForeground: "#ffffff",
    statusSuccess: "#19734a",
    statusWarning: "#946012",
    statusDanger: "#b13338",
  },
};
export const dark: PluginTheme = {
  colors: {
    surface0: "#15191f",
    surface1: "#1c222a",
    surface2: "#293342",
    border: "#3f4c5e",
    foreground: "#edf1f5",
    foregroundMuted: "#b1bdcb",
    accent: "#9ac7ff",
    accentForeground: "#102237",
    statusSuccess: "#6dddac",
    statusWarning: "#e8bd73",
    statusDanger: "#ff9b9f",
  },
};
const base: AgentItem = {
  key: "a".repeat(64),
  agentId: "agent-api",
  requestId: "request-api",
  agentTitle: "Backend · account exports",
  provider: "codex",
  workspaceId: "ws-api",
  workspaceName: "export-api",
  projectName: "Northwind",
  parentAgentId: null,
  parentAgentTitle: null,
  childAgentCount: 0,
  archiveKey: null,
  bucket: "waiting",
  lastTurn: null,
  title: "Choose a pagination strategy",
  description:
    "The export endpoint is ready for the pagination decision. UI work can continue with fixtures.",
  details: "",
  error: null,
  since: new Date(Date.now() - 24 * 60_000).toISOString(),
  form: {
    kind: "questions",
    questions: [
      {
        header: "Pagination",
        question: "How should the export endpoint paginate large result sets?",
        options: [
          {
            label: "Cursor pagination",
            description: "Stable when records change while exporting.",
          },
          {
            label: "Offset pagination",
            description: "Simpler page numbers, but inserts may shift results.",
          },
        ],
        multiSelect: false,
        allowOther: true,
        allowEmpty: false,
      },
    ],
  },
  snoozedUntil: null,
  marked: false,
  delivery: null,
};
export const initial: AgentsSnapshot = {
  fetchedAt: Date.now(),
  incomplete: false,
  workspaceIncomplete: false,
  turnHistoryIncomplete: false,
  receipts: [],
  items: [
    { ...base, childAgentCount: 1 },
    {
      ...base,
      key: "b".repeat(64),
      agentId: "agent-ui",
      parentAgentId: "agent-api",
      parentAgentTitle: base.agentTitle,
      requestId: "request-ui",
      agentTitle: "Frontend · export flow",
      provider: "claude",
      workspaceId: "ws-ui",
      workspaceName: "export-ui",
      title: "Run the focused test suite",
      since: new Date(Date.now() - 12 * 60_000).toISOString(),
      description: "The worker requests permission to run this command.",
      details: "pnpm test -- export-dialog.test.ts",
      form: {
        kind: "actions",
        actions: [
          { id: "allow", label: "Allow once", behavior: "allow" },
          { id: "deny", label: "Deny", behavior: "deny" },
        ],
      },
    },
    {
      ...base,
      key: "c".repeat(64),
      agentId: "agent-research",
      requestId: "request-research",
      agentTitle: "Storage exploration",
      provider: "pi",
      workspaceName: "storage-research",
      projectName: "Harbor",
      title: "Which storage constraints matter?",
      since: new Date(Date.now() - 7 * 60_000).toISOString(),
      description: "",
      form: {
        kind: "questions",
        questions: [
          {
            header: "Constraints",
            question: "Which constraints should the recommendation prioritize?",
            options: [
              { label: "Low operating cost", description: "" },
              { label: "Regional data residency", description: "" },
            ],
            multiSelect: true,
            allowOther: true,
            allowEmpty: false,
          },
        ],
      },
    },
    {
      ...base,
      key: "d".repeat(64),
      agentId: "agent-native",
      requestId: "request-native",
      agentTitle: "Migration review",
      since: new Date(Date.now() - 2 * 60_000).toISOString(),
      provider: "claude",
      projectName: "Harbor",
      title: "Review the proposed migration plan",
      description: "This provider uses its own plan approval controls.",
      details: JSON.stringify({ plan: "# Proposed migration plan" }),
      form: requestForm({
        kind: "plan",
        input: { plan: "# Proposed migration plan" },
      }),
    },
    {
      ...base,
      key: "e".repeat(64),
      agentId: "agent-error",
      requestId: null,
      title: "Agent needs attention",
      bucket: "failed",
      form: null,
      description: "",
      error: "The provider stopped before returning a result.",
      agentTitle: "Integration checks",
    },
    {
      ...base,
      key: "f".repeat(64),
      agentId: "agent-running",
      requestId: null,
      title: "Working",
      bucket: "running",
      form: null,
      description: "",
      agentTitle: "Documentation update",
    },
    {
      ...base,
      key: "0".repeat(64),
      agentId: "agent-finished",
      archiveKey: "3".repeat(64),
      requestId: null,
      title: "Idle",
      bucket: "idle",
      lastTurn: {
        key: "9".repeat(64),
        turnId: "turn-1",
        outcome: "completed",
        observedAt: "2026-10-04T12:00:00Z",
      },
      form: null,
      description: "",
      agentTitle: "API review",
    },
    {
      ...base,
      key: "1".repeat(64),
      agentId: "agent-idle",
      archiveKey: "4".repeat(64),
      requestId: null,
      title: "Idle",
      bucket: "idle",
      form: null,
      description: "",
      agentTitle: "Existing workspace agent",
    },
    {
      ...base,
      key: "2".repeat(64),
      agentId: "agent-closed",
      archiveKey: "5".repeat(64),
      requestId: null,
      title: "Closed",
      bucket: "closed",
      form: null,
      agentTitle: "Closed session",
    },
  ],
};
